services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: amazing_employees_list
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: node-mysql-app
    depends_on:
      - mysqldb
    links:
      - mysqldb:mysqldb
    stdin_open: true
    tty: true
    ports:
      - "80:80"
    expose:
      - "80"
